### PR TITLE
add docker healthcheck for Microsoft SQL Server on Linux

### PR DESCRIPTION
**Pull request by grillazz**

### CODE REVIEW

**Comment by tianon** [comment]
While this is neat, I don't think this repo is an appropriate place to put it -- this is exclusively for the official images.

**Comment by grillazz** [comment]
I believe you are not supporting ms products - but that is ok ;)

**Comment by grillazz** [comment]
But wait I'm working on official ms docker image - should I clean my dockerfile ?

**Comment by tianon** [comment]
The name is a bit unfortunate, but I'm referring specifically to images from Docker's "Official Images" program (https://github.com/docker-library/official-images and https://hub.docker.com/explore/).  There are some Windows-based image tags there, but the images under `microsoft/...` (or any other user/organization, for that matter) are not included.

**Pull request closed without merging**
